module.exports.getPrefix = () => FW.prefix;
module.exports.getLocale = () => FW.Locale;
module.exports.getUserGroup = () => FW.User_Group;
module.exports.getPath = () => FW.path;
module.exports.getCurrency = () => FW.Context.c;
module.exports.getContext = () => FW.Context;
module.exports.getToken = () => FW.token;
module.exports.getUrl = () => FW.URL;
module.exports.getSiteStatic = () => FW.site_static;
module.exports.getCallUrlPrefix = () => FW.call_url_prefix;
module.exports.getCallUrlPrefix = () => FW.call_url_prefix;
module.exports.getUuid = () => FW.uuid;
module.exports.getInitialState = () => FW.initial;
module.exports.supported = () => FW !== undefined;
module.exports.GET = FW.GET;
module.exports.getMode = () => FW.mode;